flags:
  hakyll:
    previewserver: false
    watchserver:   false
    checkexternal: false
  pandoc:
    https: false
  pandoc-citeproc:
    bibutils: false
packages:
- '.'
extra-deps:
- hakyll-4.9.5.1
- pandoc-1.19.2.1
- pandoc-citeproc-0.10.4.1
resolver: lts-8.3
